import {Task} from "./types";
export const tasks:Task[]=[
{id:"T-1048",title:"Lock hero selects for fall campaign",brand:"ARRA",client:"Northstar Goods",project:"Fall / Winter 2026",assignee:"Maya Chen",initials:"MC",status:"In progress",priority:"Urgent",due:"2026-08-14",kind:"Task"},
{id:"D-218",title:"Launch film — client review",brand:"ARRA",client:"Northstar Goods",project:"Fall / Winter 2026",assignee:"Jonathan Ibarra",initials:"JI",status:"Needs approval",priority:"High",due:"2026-08-16",kind:"Deliverable",working:"https://drive.google.com",review:"https://frame.io"},
{id:"T-1054",title:"Revise social cutdowns v3",brand:"SQUATCH",client:"Roam Coffee",project:"Built for the trail",assignee:"Elena Ruiz",initials:"ER",status:"Revisions",priority:"High",due:"2026-08-16",kind:"Task"},
{id:"D-224",title:"Product photography finals",brand:"ARRA",client:"Aster House",project:"Objects of ritual",assignee:"Maya Chen",initials:"MC",status:"In progress",priority:"Normal",due:"2026-08-16",kind:"Deliverable",working:"https://drive.google.com"},
{id:"T-1060",title:"Finalize creator shortlist",brand:"SQUATCH",client:"Fieldwork",project:"Away, together",assignee:"Noah Williams",initials:"NW",status:"Not started",priority:"Normal",due:"2026-08-18",kind:"Task"},
{id:"D-229",title:"Brand anthem sound mix",brand:"ARRA",client:"Northstar Goods",project:"Fall / Winter 2026",assignee:"Jonathan Ibarra",initials:"JI",status:"Needs approval",priority:"Normal",due:"2026-08-19",kind:"Deliverable",working:"https://drive.google.com",review:"https://frame.io"},
{id:"T-1066",title:"Build paid media trafficking sheet",brand:"SQUATCH",client:"Roam Coffee",project:"Built for the trail",assignee:"Elena Ruiz",initials:"ER",status:"Not started",priority:"Low",due:"2026-08-21",kind:"Task"},
{id:"D-231",title:"Campaign toolkit handoff",brand:"ARRA",client:"Aster House",project:"Objects of ritual",assignee:"Maya Chen",initials:"MC",status:"Complete",priority:"Normal",due:"2026-08-12",kind:"Deliverable",final:"https://drive.google.com"}
];
export const clients=[{name:"Northstar Goods",brand:"ARRA",projects:3,contact:"Amelia Hart",health:"On track"},{name:"Roam Coffee",brand:"SQUATCH",projects:2,contact:"Dean Park",health:"At risk"},{name:"Aster House",brand:"ARRA",projects:2,contact:"Carmen Wells",health:"On track"},{name:"Fieldwork",brand:"SQUATCH",projects:1,contact:"Jules Martin",health:"On track"}];
export const projects=[{name:"Fall / Winter 2026",client:"Northstar Goods",brand:"ARRA",progress:68,due:"Sep 04"},{name:"Built for the trail",client:"Roam Coffee",brand:"SQUATCH",progress:54,due:"Aug 28"},{name:"Objects of ritual",client:"Aster House",brand:"ARRA",progress:86,due:"Aug 22"},{name:"Away, together",client:"Fieldwork",brand:"SQUATCH",progress:31,due:"Sep 18"}];
